const UserTypes = {
  LOGIN_USER_OBJECT: 'LOGIN_USER_OBJECT',
  LOGIN_USER_ERROR_OBJECT: 'LOGIN_USER_ERROR_OBJECT',

  FETCH_CURRENT_USER_SUCCESS: 'FETCH_CURRENT_USER_SUCCESS',
  LOG_OUT_USER: 'LOG_OUT_USER',
};

export default UserTypes;
